# -*- python -*-

import os, sys
from distutils import sysconfig
import glob

env = Environment(
    CCFLAGS = [ '-O2', '-W', '-Wall' ],
#    CCFLAGS = [ '-g', '-W', '-Wall' ],
    CPPDEFINES = [
#        'NDEBUG',
#        'ENABLE_DEBUG_FN',
#        'ENABLE_DEBUG_PRINT',
#        'ENABLE_TEST',
#        'ENABLE_BENCHMARK',
    ],
    CPPPATH = ['.'],
    ENV = os.environ,
    LIBS = [ 'boost_python-mt', 'boost_thread-mt' ],
)

# hack to remove compiler flags from the distutils default.
# -Wstrict-prototypes is not valid for C++
cv_opt = sysconfig.get_config_var('CFLAGS')
cflags = [ x for x in cv_opt.split() if x not in ['-g', '-O2', '-Wstrict-prototypes', '-DNDEBUG'] ]
env.Append(CCFLAGS = cflags)

env.Append(CPPPATH = [sysconfig.get_python_inc(plat_specific=1)],
           LIBPATH = [sysconfig.get_python_lib(plat_specific=1)])

env.ParseConfig(
    'pkg-config --cflags --libs alsa jack'
)

env.SharedLibrary('_mididings', [
        'backend_alsa.cc',
        'engine.cc', 'patch.cc', 'units.cc',
        'python_caller.cc', 'python_module.cc'
    ],
    SHLIBPREFIX='', SHOBJSUFFIX='.o'
)
